import { ShieldCheck } from "lucide-react";

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen pt-24 pb-12 px-6 flex flex-col items-center">
      <div className="w-full max-w-4xl space-y-12">
        <div className="text-center space-y-4">
          <div className="mx-auto w-16 h-16 rounded-2xl bg-gradient-to-br from-primary to-secondary flex items-center justify-center shadow-[0_0_30px_rgba(0,210,255,0.4)] mb-6">
            <ShieldCheck size={32} className="text-black" />
          </div>
          <h1 className="text-4xl md:text-5xl font-black tracking-tighter text-white">
            Terms of Service
          </h1>
          <p className="text-sm md:text-base text-text-secondary max-w-2xl mx-auto">
            Last updated: March 2026
          </p>
        </div>

        <div className="glass-panel p-8 md:p-12 rounded-[32px] space-y-8 animate-entrance prose prose-invert max-w-none">
          <p className="text-text-secondary">
            Please read these Terms of Service completely before using our platform. Your access to and use of the service is conditioned on your acceptance of and compliance with these terms.
          </p>

          <h3 className="text-xl font-bold text-white mt-8 mb-4">1. Acceptance of Terms</h3>
          <p className="text-text-secondary">
            By registering for an account and using our services, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.
          </p>

          <h3 className="text-xl font-bold text-white mt-8 mb-4">2. User Accounts</h3>
          <p className="text-text-secondary">
            When creating an account, you must provide accurate and complete information. You are responsible for safeguarding the password that you use to access the service and for any activities or actions under your password.
          </p>

          <h3 className="text-xl font-bold text-white mt-8 mb-4">3. Acceptable Use</h3>
          <p className="text-text-secondary">
            You agree not to use the service for any unlawful purpose or in any way that interrupts, damages, or impairs the service. Generating malicious, abusive, or explicitly harmful prompts may result in immediate account termination.
          </p>

          <h3 className="text-xl font-bold text-white mt-8 mb-4">4. Intellectual Property</h3>
          <p className="text-text-secondary">
            The service and its original content (excluding prompts generated by users), features, and functionality are and will remain the exclusive property of AI Prompt Generator and its licensors.
          </p>
          
          <h3 className="text-xl font-bold text-white mt-8 mb-4">5. Limitation of Liability</h3>
          <p className="text-text-secondary">
            In no event shall AI Prompt Generator, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages resulting from your use of the service.
          </p>
        </div>
      </div>
      
      {/* Background Decorative Blur */}
      <div className="fixed inset-0 bg-midnight-flow -z-10" />
    </main>
  );
}
